<template>
  <div class="flex flex-col items-center justify-center h-screen bg-gray-100">
    <h1 class="text-3xl font-bold mb-4">MTG Card Generator</h1>
    <div class="flex flex-col items-center">
      <input
        v-model="prompt"
        class="border border-gray-400 rounded-md px-4 py-2 w-80 mb-4"
        placeholder="Enter a prompt"
      />
      <button
        @click="generateCard"
        class="bg-blue-500 hover:bg-blue-600 text-white rounded-md px-4 py-2"
      >
        Generate Card
      </button>
      <button
        @click="generateSampleCard"
        class="bg-gray-500 hover:bg-gray-600 text-white rounded-md px-4 py-2 mt-4"
      >
        Generate Sample Card
      </button>
    </div>
    <CardComponent
      v-if="gptOutput"
      :cardTitle="cardProperties.name"
      :cardCost="cardProperties.cost"
      :cardType="cardProperties.type"
      :cardDescription="cardProperties.abilities"
      :cardPower="cardProperties.power"
      :cardToughness="cardProperties.toughness"
      :cardArt="cardProperties.art"
    />
    <div v-if="gptOutput" class="mt-8">
      <div class="card">
        <div class="card-content">
          <div class="text-med">{{ gptOutput }}</div>
        </div>
      </div>
      <div>
        <p
          v-for="(value, key) in cardProperties"
          :key="key"
          class="flex justify-center w-auto bg-red-400 rounded mt-2 p-2"
        >
          {{ key }}: {{ value }}{ñ}
        </p>
      </div>
    </div>
  </div>
</template>

<script>
import CardComponent from "@/components/CardComponent.vue";

export default {
  name: "Home",
  components: { CardComponent },
  data() {
    return {
      prompt: "",
      gptOutput: "",
      cardProperties: {
        name: "",
        cost: "",
        type: "",
        power: "",
        art: "",
        toughness: "",
        abilities: "",
      },
      regex:
        /(.+?)\nMana Cost: (.+?)\nType: (.+?)\nPower\/Toughness: (.+?)\nAbilities: (.+)/s,
    };
  },
  methods: {
    async generateCard() {
      if (!this.prompt) {
        return;
      }

      this.gptOutput = "";
      this.cardProperties = {
        name: "",
        cost: "",
        type: "",
        power: "",
        toughness: "",
        abilities: "",
        art: "", // Add the art property here
      };

      const prompt = `Generate a Fanmade Magic The Gathering creature card of ${this.prompt}, the text should be generated to match the following regex ${this.regex}, also make sure that our output method expects your mana costs to be in a format like for example: {2}{B}{B} for 2BB, same for activate abilities, or {T} for tap action, and so on with the rest... Do not include flavor text. You are not generating images or graphics.`;
      const artPrompt = `Magic The Gathering creature of ${this.prompt}, Magic The Gathering Art Style, creature should have respective action pose and background related to the creature backstory.`;

      const response = await fetch("http://127.0.0.1:5000/generate-card", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ prompt, artPrompt }), // Pass both prompts to the API
      });

      if (response.ok) {
        const cardInfo = await response.json();
        this.gptOutput = cardInfo.gpt_output;
        this.cardProperties.art = cardInfo.image_urls[0]; // Assign the first image URL to art property

        // Extract card properties using regular expressions
        const matches = this.gptOutput.match(this.regex);

        if (matches) {
          this.cardProperties = {
            name: matches[1].trim(),
            cost: matches[2].trim(),
            type: matches[3].trim(),
            power: matches[4].trim().split("/")[0],
            toughness: matches[4].trim().split("/")[1],
            abilities: matches[5].trim(),
            art: cardInfo.image_urls[0], // Assign the first image URL to art property
          };
        }
      }
    },
    generateSampleCard() {
      this.gptOutput =
        "Sample Card\n\nMana Cost: 1 Red 1 Blue\n\nCard Type: Creature\n\nPower/Toughness: 2/2\n\nCard Text: This is a sample card generated by the app.\n\nFlavor Text: Enjoy!\n\nRarity: Common";
      this.cardProperties = {
        name: "Sample Card",
        cost: "1R1B",
        type: "Creature",
        power: "2",
        toughness: "2",
        abilities: "Sample abilities",
      };
    },
  },
};
</script>

<style>
.card {
  width: 600px;
  height: auto;
  background-color: white;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  display: flex;
  align-items: center;
  justify-content: center;
}

.card-content {
  padding: 16px;
  text-align: center;
}

.text-med {
  font-size: 24px;
  line-height: 1.5;
}
</style>
