<template>
  <div class="flex flex-col items-center justify-center h-screen bg-gray-100">
    <h1 class="text-3xl font-bold mb-4">MTG Card Generator</h1>
    <div class="flex flex-col items-center">
      <input
        v-model="prompt"
        class="border border-gray-400 rounded-md px-4 py-2 w-80 mb-4"
        placeholder="Enter a prompt"
      />
      <button
        @click="generateCard"
        class="bg-blue-500 hover:bg-blue-600 text-white rounded-md px-4 py-2"
      >
        Generate Card
      </button>
      <button
        @click="generateSampleCard"
        class="bg-gray-500 hover:bg-gray-600 text-white rounded-md px-4 py-2 mt-4"
      >
        Generate Sample Card
      </button>
    </div>
    <div v-if="gptOutput" class="mt-8">
      <div class="card">
        <div class="card-content">
          <div class="text-med">{{ gptOutput }}</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Home",
  data() {
    return {
      prompt: "",
      gptOutput: "",
    };
  },
  methods: {
    async generateCard() {
      if (!this.prompt) {
        return;
      }

      this.gptOutput = "";

      const prompt = `Generate a Magic: The Gathering card with the following prompt: ${this.prompt}`;
      const response = await fetch("http://127.0.0.1:5000/generate-card", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ prompt }),
      });

      if (response.ok) {
        const cardInfo = await response.json();
        this.gptOutput = cardInfo.gpt_output;
      }
    },
    generateSampleCard() {
      this.gptOutput = "Sample Card\n\nMana Cost: 1 Red 1 Blue\n\nCard Type: Creature\n\nPower/Toughness: 2/2\n\nCard Text: This is a sample card generated by the app.\n\nFlavor Text: Enjoy!\n\nRarity: Common";
    },
  },
};
</script>

<style>
.card {
  width: 400px;
  height: 560px;
  background-color: white;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  display: flex;
  align-items: center;
  justify-content: center;
}

.card-content {
  padding: 16px;
  text-align: center;
}

.text-med {
  font-size: 24px;
  line-height: 1.5;
}
</style>
